# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: time.proto for package 'grpctest.time.v1'
# Original file comments:
# time.proto
#

require 'grpc'
require 'time_pb'

module Grpctest
  module Time
    module V1
      module TimeService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'grpctest.time.v1.TimeService'

          rpc :GetCurrentTime, ::Grpctest::Time::V1::GetCurrentTimeRequest, ::Grpctest::Time::V1::GetCurrentTimeResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
