# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time.proto

require 'google/protobuf'


descriptor_data = "\n\ntime.proto\x12\x10grpctest.time.v1\"\x17\n\x15GetCurrentTimeRequest\"&\n\x16GetCurrentTimeResponse\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t2r\n\x0bTimeService\x12\x63\n\x0eGetCurrentTime\x12\'.grpctest.time.v1.GetCurrentTimeRequest\x1a(.grpctest.time.v1.GetCurrentTimeResponseB\nZ\x08pkg/timeb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Grpctest
  module Time
    module V1
      GetCurrentTimeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpctest.time.v1.GetCurrentTimeRequest").msgclass
      GetCurrentTimeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpctest.time.v1.GetCurrentTimeResponse").msgclass
    end
  end
end
